### PR TITLE
Fix zip Upload

### PR DESCRIPTION
**Pull request by klas**
Fix zip uploading when Forbidden file extensions in zip is set to None

### CODE REVIEW

**Comment by pulsarinformatique** [comment]
Hi

thanks, works for me

cyril

**Comment by pulsarinformatique** [comment]
Hi Klas
It seems your fix has been discarded again with the 3.9.0 release !! why again ?
Cyril

**Comment by pulsarinformatique** [comment]
Hi Klas and Saba
It seems your fix has been discarded again with the 3.10.0 release !! why again and again? 
Cyril

**Comment by sebastienheraud** [comment]
Hi Cyril,
Of course all PRs could have been included in 3.10.0, and also all issues fixed in 3.10.0 ... and I would have released the 3.10.0 next year.
Is it better to fix EVERYTHING and to wait another 3 months or so to release a package, instead of bringing improvements right now... I don't think so...
Can we say that "Admin/Site Forms", "Google API", "Timezone", "Versions" are used by (almost) everyone, and that uploading ZIP archives containing PHP/INI/PL files... is a less common use? Yes I think so...
It still appear as a Joomla! core issue to me, and so yes this workaround may someday be included... but it won't replace a proper fix. Feel free to use it until something new comes up.
Saba

**Comment by pulsarinformatique** [comment]
Hi Saba
If this is a J! core issue did you submit it to the J! git ?

thanks

cyril

**Pull request closed without merging**
