### PR TITLE
Fix calendar problems

### LINKED ISSUE #317: Date field : day and month are switched using d/m/Y date format
Hi,
I found a bug with the date field, but only when using the **d/m/Y date format** in multi-stage forms.
When going from step 1 to 2, then back to 1, the day and the month are switched.

I made [this URL ](http://mat0.odns.fr/pal.createur.pro/test-date-r-w) to show the problem.
1/ use the calendar to input the same date (ex 01/11/2016 and 01-11-2016),
2/ Click Next,
3/ Click Previous,
4/ The first date shows 11/01/2016 (day and month are switched), but the second date is correct, showing 01-11-2016.
This only happens **when "text input" is enabled**.
This doesn't happen when using the d-m-Y format, or with "text input" disabled.

Second bug : choosing a date in which the day is >12th of month makes an error (DateTime::__construct(): Failed to parse time string (14/11/2016) at position 0 (1): Unexpected character).
This also only happens when using the same parameters (d/m/Y date format, and "text input" enabled) the field with the "-" works OK.

I am using pure vanilla Joomla 3.6.4 + Seblod 3.10.0, with default calendar field parameters (except of course with "text input" enabled).
Problem has been reported [here](https://www.seblod.com/community/forums/fields-plug-ins/date-bug-in-multi-page-forms) in the forum (and confirmed by user mlep).

I guess there is a problem with the way the "/" are handled...

### PR DESCRIPTION
**Pull request by klas**
Add $field->text property calculation to onCCK_FieldPrepareStore to be used by the email field to get formated value. 
Also timestamp fworks now including javascript to switch storage type.

Reference http://www.seblod.com/community/forums/forms-content-types/calender

Also fixes problem with default values "now", "today" etc having time delay (reported by Lisa)

Also fixes #317 (day and month switched after save) and removes a lot of unnecessary code.

### CODE REVIEW

**Comment by klas** [comment]
tests ok by sandrawe67 on the forum

**Comment by klas** [comment]
I need to improve this a bit more, it has problem with word default/live values (now. today etc), will fix this today

**Comment by klas** [comment]
done

**Comment by klas** [comment]
Also fixes https://github.com/Octopoos/SEBLOD/issues/346

**Comment by pulsarinformatique** [comment]
Hi
When I use the new calendar.php file I get this error in the backend (when editing a content with the calendar field)

Fatal error: Can't use function return value in write context in /plugins/cck_field/calendar/calendar.php on line 79

thanks

cyril

**Comment by klas** [comment]
There is nothing on line 79 of the new field
https://github.com/klas/SEBLOD/blob/3974e5c847d96c8124f09db5efcc4f4601f3d1b2/plugins/cck_field/calendar/calendar.php#L79

**Comment by pulsarinformatique** [comment]
Hi Klas

sorry my copy/paste did add a blank line at the start of the file

anyway the error still remains and it's the line 

$value		=	( !empty(trim( $value )) ) ? trim( $value ) : trim( $field->defaultvalue );

**Comment by klas** [comment]
ok, you are obviously using old php version, will adjust the pull http://stackoverflow.com/questions/17139264/cant-use-function-return-value-in-write-context

**Comment by pulsarinformatique** [comment]
ok but now

if you set l d-m-Y H:i in the format nothing will be stored in the data base when you save your content
it is the "l" that causes the issue

not all the format tags (http://php.net/manual/fr/function.date.php) seem to be supported

cyril

**Comment by pulsarinformatique** [comment]
For instance on a PHP5.6 server try to put d-F-Y in the calendar field format you get the following error:

Fatal error: Call to a member function format() on boolean in /plugins/cck_field/calendar/calendar.php on line 196

**Comment by klas** [comment]
Calendar supports any format supported by Joomla JDate->format, which should suport all tags supported by php.

But in your case I would think that you did not apply patch correctly as error you mention can't happen on line 196 https://github.com/klas/SEBLOD/blob/3974e5c847d96c8124f09db5efcc4f4601f3d1b2/plugins/cck_field/calendar/calendar.php#L196 
I suggest you downwload the whole changed file and replace calendar.php with it.

**Comment by pulsarinformatique** [comment]
Strange, I exactly downoaded the whole new file !

**Comment by pulsarinformatique** [comment]
Klas I confirm the issue with the whole new downloaded file. Don't be fooled by the line number because in my code I had to modify the line 

$value	=	( !empty(trim( $value )) ) ? trim( $value ) : trim( $field->defaultvalue );

into

$trimValue= trim( $value );
		if ( !empty($trimValue) )
		{
		$value		=	 trim( $value ) ;
		}
		else{
		$value		=	 trim( $field->defaultvalue );
		}

Thanks

Cyril

**Comment by klas** [comment]
I updated the pull for older php version compatibility.

**I re-tested field with d-m-Y H:i and d-F-Y and they both work fine.**

There must be something seriously wrong with your php, could be problem is that you don't have french support compiled in php  Try if all examples from http://php.net/manual/fr/function.date.php work for you

**Comment by pulsarinformatique** [comment]
Klas

we tested this with several different servers with different PHP versions. 
with the last calendar.php on the github when I save a content with a calendar field set up with d-F-Y I get the error message :
Fatal error: Call to a member function format() on boolean in /plugins/cck_field/calendar/calendar.php on line 244

I'm here on PHP 5.6.24

**Comment by pulsarinformatique** [comment]
it's true however I don't get the error if the backend is in english
but once the backend is in french, if the calendar field is set (for example) to d-F-Y it crashes when you save the content

**Comment by klas** [comment]
The only way I can reproduce this is to set locale that does not exist on server in my active language. ALl we can do here is to report a more meaningful error.

So in your case your server need to have support for one of locales set in french language file: <locale>fr_FR.utf8, fr_FR.UTF-8, fr_FR.UTF-8@euro, fr_FR, fre_FR, fr, france</locale>

You can see which locales are supported on server if you do  locale -a on command line

**Comment by pulsarinformatique** [comment]
a locale -a on one of our servers yields  ::

C
C.UTF-8
en_US.utf8
français
french
fr_FR
fr_FR@euro
fr_FR.iso88591
fr_FR.iso885915@euro
fr_FR.utf8
fr_FR.utf8@euro
POSIX

Again we hadn't this issue with the previous calendar.php on any of our servers
thanks

cyril

**Comment by klas** [comment]
We hit a php bug - for some really weird reason DateTime::::createFromFormat works fine with some languages beside English  e.g. German and Slovenian that I tested with, but it does not work with French date names. 

I will rework the pull to get around this.

**Comment by pulsarinformatique** [comment]
at last, great to read this :) we will test the new version, you can be sure :)

thanks !

**Comment by klas** [comment]
I re-added hidden field with unformated value which will do the job when calendar-only is used. But as soon as manual input is allowed we neeed a library capable of parsing international language strings like the one mentioned by @pulsarinformatique - here https://github.com/jenssegers/date comes to the rescue. We should think about disabling this option alltogether in the future incarnations of the calendar.

**Comment by pulsarinformatique** [comment]
Thanks Klas, did you test it on the test site I sent you ?

**Comment by klas** [comment]
yes. it works fine

**Comment by pulsarinformatique** [comment]
Yes I confirm the issue is SOLVED. Thanks

cyril

**Comment by pulsarinformatique** [comment]
Hi
We found another issue related to this first issue. 
In a French site if you set "l d F Y à H:i" in the format AND create a seach list with this field in the search tab, any search will crash.

A textual day could not be found Unexpected data found. A textual month could not be found Data missing

thanks

cyril

**Comment by klas** [comment]
l d F Y à H:i is not a valid date format, you can't just write in something and expect it to work. If you remove à it should work.

**Comment by pulsarinformatique** [comment]
Please use l d F  Y


In the search it will crash

Thanks



Envoyé depuis mon smartphone Samsung Galaxy.


-------- Message d'origine --------
De : Klas <notifications@github.com>
Date : 17/03/2017 15:17 (GMT+01:00)
À : Octopoos/SEBLOD <SEBLOD@noreply.github.com>
Cc : Pulsar Informatique <info@pulsar-informatique.com>, Mention <mention@noreply.github.com>
Objet : Re: [Octopoos/SEBLOD] Fix calendar problems (#199)


l d F Y à H:i is not a valid date format, you can't just write in something and expect it to work. If you remove à it should work.

**Comment by klas** [comment]
Ok, I will check, but please consider that no library will be able to parse just some made up format containing letters like à - you need to use only letters defined in http://php.net/manual/en/function.date.php and even them in one of the standard formats http://php.net/manual/en/datetime.formats.date.php

**Comment by klas** [comment]
Ok, try now. We need to use get variables here, not post as in form. Also intval can't deal with french dates, intval("Mardi 21 Mars 2017") returns 0.. php is such a buggy languages sometimes.

Thank you for finding this bugs before release.

**Comment by pulsarinformatique** [comment]
yes fixed !

thanks !

**Comment by klas** [comment]
It has been decided that 3rd party date library is not going to be included, so I removed it. 

**When using Calendar fields with international dates that include textual day/month names you should not allow manual entry**  (or reverse, use valid date format that does not include textual names - in English it work ok with standard PHP functions)

**Comment by pulsarinformatique** [comment]
Ok Klas

as long as the calendar accepts "l d F  Y" format it's ok for us since it is a standard format. if not it will still be an issue.

I understand however it won't accept "à" and we accept it.

thanks

cyril

**Comment by klas** [comment]
Lowercase l won't work, it is textual representation of the day (or better said it would work for English names, but not for French and others)

**Comment by pulsarinformatique** [comment]
So the calendar plugin doesn't support all the standard formats of http://php.net/manual/fr/function.date.php

**Comment by sebastienlapoux** [comment]
Hi,
@klas please stop to work on this issue.
@pulsarinformatique if you wish some work on this topic pleas contact Octopoos for a work payed.
Thanks.

**Comment by pulsarinformatique** [comment]
It is your choice to fix or not to fix this point and it is our choice to report it :)

As usual I regret this brutal tone.

**Comment by sebastienheraud** [comment]
Hello,
File merged.
Thanks,
Saba

**Pull request merged**
