### PR TITLE
Calendar - properly handle live/default values in form and search

### PR DESCRIPTION
**Pull request by klas**
Fix issue with live values like now in search, also improve processing in form to get the same value submited for live and default and also prevent submitting value when value is emtpy (not set by either user/live/default)

### CODE REVIEW

**Comment by Mat-o** [comment]
Hi Klas,
Maybe this PR could help with the date validation plugin issue : [https://github.com/Octopoos/SEBLOD_more/issues/6](https://github.com/Octopoos/SEBLOD_more/issues/6)
Il will try and report.

**Comment by klas** [comment]
Isomehow doubt it will help as issue was with live value like "now" not working on server side while validations work on client side

**Comment by svenlewerentz** [comment]
Hi Klas, this fixes the issue in my installation.

**Comment by GBob1789** [comment]
Hi Klas, It's ok for me with the fix.

**Comment by sebastienheraud** [comment]
Hello,
Merged.
Thank you,
Saba.

**Comment by coolcat-creations** [comment]
Works thanks!

**Pull request merged**
