### PR TITLE
Cache fixes

### PR DESCRIPTION
**Pull request by klas**
Copy pull https://github.com/Octopoos/SEBLOD/pull/30 to master branch

Pelase see comments there as this thread here is not complete.

### CODE REVIEW

**Comment by Bucklash** [comment]
This fix put a stop to my scenario:
Contact Form not submitting

https://www.seblod.com/community/forums/fields-plug-ins/submit-button-and-cache#post49067

**Comment by klas** [comment]
as it is a bit unclear - "put a stop" here means it has fixed the problem.

**Comment by sebastienheraud** [comment]
Hello,
It is now merged. Thanks Klas!
Quick fix applied afterward here: https://github.com/Octopoos/SEBLOD/commit/7eeb390b2cf628e32947b9d99e7ae242aa9a3ea7
Regards,
Saba.

**Comment by sebastienheraud** [comment]
Additional note:
This version of the file is the proper one: https://github.com/Octopoos/SEBLOD/blob/fca665bfb78ab4e5f36dc762b3482d2b7301c4e0/components/com_cck/controller.php after I reverted some other upcoming changes (that was merged in my initial fix)
Saba.

**Comment by klas** [comment]
Thnx Saba

**Pull request merged**
