### PR TITLE
Implement access to $config variable in replaceLive function

### PR DESCRIPTION
**Pull request by steve-genilogic**
Further to my question in the forums https://www.seblod.com/community/forums/fields-plug-ins/what-variables-are-accessible-to-select-dynamic, I have implemented the ability to access the $config variable in the replaceLive function. I feel this would be useful to a wider audience, hence this PR.

### CODE REVIEW

**Comment by steve-genilogic** [comment]
Any thoughts on whether this might get merged? @sebastienheraud @sebastienlapoux

**Comment by steve-genilogic** [comment]
Any chance of merging this in with 3.20.0 release?

**Comment by sebastienheraud** [comment]
Hi @steve-genilogic,

These new `$context->...` should help:
* https://github.com/Octopoos/SEBLOD/commit/ef93de4f51e39a1ad083f388ffce9cb205dff2fd
* https://github.com/Octopoos/SEBLOD/commit/c73ef8cec1537523642ee8d9e9f23c44a96c7a18

Is that OK for now? (safer for future changes related to $config)

Thanks,  
Saba

**Comment by steve-genilogic** [comment]
Hi @sebastienheraud,

That's excellent, thank you!

Happy to close this and use the `$context` methods instead.

Cheers,

Steve

**Comment by sebastienheraud** [comment]
👍

**Pull request closed without merging**
