### PR TITLE
Fix problems with caching on and search&lists

### PR DESCRIPTION
**Pull request by klas**
Fixes
http://www.seblod.com/resources/tracker/5365
http://www.seblod.com/resources/tracker/13082

### CODE REVIEW

**Comment by MaierGrem** [comment]
Thanks! Search operation is performed once, and then writes the values ​​in the cache. And then the new values ​​are not sent. Input fields contains old value, but page was reloaded. If array ($safeurlparams) contains all field names from Search Forms - it works.

Regards

**Comment by MaierGrem** [comment]
Have you any ideas how solved this problem?

**Comment by klas** [comment]
I have updated the pull to  3.3.7.
@MaierGrem please download https://raw.githubusercontent.com/klas/SEBLOD-bugfixed/master/components/com_cck/controller.php and replace frontend component controler with it and see if it works. If it doesn't please give me detailed instructions how to reproduce the problem. 

I have tested this pull with multiple lists on the same page using search or not and in both - component and module and it works as expected in all instances.,

**Comment by MaierGrem** [comment]
@Klas, thanks, I'll check when I get home from vacation!

**Comment by PierreCorell** [comment]
I tested it with a module on frontpage directing to a list, and at the list itself, of course.
It works as expected, if the Joomla! page cache is off.

**Comment by klas** [comment]
HI, thnx for testing, yes, page cache plugin needs to be off, that is another type of caching not suitable for dynamic pages.

**Comment by sebastienheraud** [comment]
As a ref: http://www.seblod.com/community/forums/general-discussions/optimal-server-settings-for-faster-pageload#post37772
Saba

**Comment by klas** [comment]
see #171

**Pull request closed without merging**
