### PR TITLE
Cleanup & Improvments

### PR DESCRIPTION
**Pull request by viocassel**
Added SEBLOD logo and bootstrap markup to "postflight".
dd01b1b0ba7945359165eddb4dfbe545

### CODE REVIEW

**Comment by viocassel** [comment]
Added some cleanup and fixes (CSS).

**Comment by sebastienheraud** [comment]
Hello Vio,
Thank you, I'm merging this PR
I may need to revert the translation strings. Will check.
Saba.

**Comment by sebastienheraud** [comment]
Translation file is now forced, so everything is good even for installation:
https://github.com/Octopoos/SEBLOD/commit/3b0bc5874d72b39f9af9cde95c53dfdc0fa178a3
Thanks,
Saba.

**Comment by viocassel** [comment]
Thanks Saba!

**Pull request merged**
