### PR TITLE
Task Id retrieving/applying fix

### PR DESCRIPTION
**Pull request by olivier-nolbert**
Fixes the retrieving of the stored task Id value in JSON for the field editing and the applying of it in the JS code for it to be processed.

### CODE REVIEW

**Comment by olivier-nolbert** [comment]
Hi Saba,

We've seen the same issue in another part of the submit.php file code. We've put the fix in a protected method of the plugin to avoid duplicated code.

How do you want to proceed ?

Cheers

**Comment by sebastienheraud** [comment]
Hi Olivier,
Thanks again for reporting, for the update, and sorry for the delay.

I had a deeper look into it and I found the root cause:
After removing JRequest https://github.com/Octopoos/SEBLOD/commit/1013b22b9ad94120c0fc19cc040193d148a58261, an additional fix https://github.com/Octopoos/SEBLOD/commit/787b44ac4e6aaa00a48046d5d62dd31ca602aca1 was applied within the wrong file. It should have been done in administrator/components/com_cck/models/field.php instead.

Fix https://github.com/Octopoos/SEBLOD/commit/5dc2fec7fcc04d0104146a7a393868f2149ccab1 included in 3.23.2 Release Candidate ... so no change needed in the Submit button, everything is already there in "onCCK_FieldConstruct" which now should be executed properly.

Feel free to have a try with the Release Candidate, and please confirm.
The following SQL update is run from the package update: https://github.com/Octopoos/SEBLOD/blob/467b2012a1ea9c90be38b63333a3f4966b943fd4/administrator/components/com_cck/install/upgrades/3.23.2.sql

Saba

**Comment by sebastienheraud** [comment]
All good with https://github.com/Octopoos/SEBLOD/pull/635#issuecomment-1435690982 @olivier-nolbert? 

Thanks,
Saba

**Comment by olivier-nolbert** [comment]
Hi Saba,

Yes, it ok with this one.

Cheers

**Comment by sebastienheraud** [comment]
Thanks :)
Will rename the 3.x RC, and will check to have the same fix/code within the upcoming 4.x rp8
Saba

**Pull request closed without merging**
