### PR TITLE
Allow correct creation of categories

### PR DESCRIPTION
**Pull request by klas**
add workaround for categories too.

Alternatively it would be perhaps better to have instances public to methods like this can be run on it.

### CODE REVIEW

**Comment by Bucklash** [comment]
Hi Klas

Going all out on guess work here.
Would tags be included, too?

if ( $this->_object == 'joomla_menu_item' || $this->_object == 'joomla_category' || $this->_object == 'joomla_tags')

**Comment by Bucklash** [comment]
Sorry  'joomla_tag', not 'joomla_tags'

**Comment by sebastienheraud** [comment]
Hi Klas,
The JCckContent class has already been improved in this way, but it has not been committed yet.
I'm gonna commit this morning so you can have a look/try.
Saba

**Comment by sebastienheraud** [comment]
Hey,
Here is the commit with all the changes related to JCckContent: https://github.com/Octopoos/SEBLOD/commit/b4f03b3d029c5f0c4fd135745a6e8d3847486287
Additional info in changelog: https://github.com/Octopoos/SEBLOD/commit/6f19a9c4638ddbbf2fd059824655a20ef694f0d3
@klas let me know if you see something wrong.
Saba

**Comment by sebastienheraud** [comment]
Requested fix here: https://github.com/Octopoos/SEBLOD/commit/012659afd1ce8aa9447a2b84fa50b63a5b4056a3
@klas I guess, one check/test is missing (this shouldn't be called all the time..)
@Bucklash you are right, same code applies to joomla_tag object.
I will commit later at https://github.com/Octopoos/SEBLOD_more
Thanks,
Saba.

**Comment by Bucklash** [comment]
Hi

Woukd bridge support be built in or would it be an additional step?
I'm not able to read the code well enough to try and work out if that woukd be the case...

**Comment by sebastienheraud** [comment]
Hi all,
Here is the latest fix for the creation of category: https://github.com/Octopoos/SEBLOD/commit/5dc9558b213d74f240904c7dc29318b0567c3e90
Regards,
Saba.

**Pull request closed without merging**
